# Generated by Django 4.2.2 on 2023-06-07 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=7)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birthdate', models.DateField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookstoreWeb.address')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookstoreWeb.address')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookstoreWeb.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookstoreWeb.address')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookstoreWeb.address')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookstoreWeb.store')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookstoreWeb.orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookstoreWeb.staff'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Mystery', 'Mystery'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Historical Fiction', 'Historical Fiction'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Literary Fiction', 'Literary Fiction'), ('Young Adult', 'Young Adult'), ('Contemporary Fiction', 'Contemporary Fiction'), ('Biography', 'Biography'), ('History', 'History'), ('Memoir', 'Memoir'), ('Self-help', 'Self Help'), ('Science', 'Science'), ('Business', 'Business'), ('Psychology', 'Psychology'), ('Philosophy', 'Philosophy'), ('Travel', 'Travel'), ('Cookbooks', 'Cookbooks'), ('Picture Books', 'Picture Books'), ('Early Readers', 'Early Readers'), ('Chapter Books', 'Chapter Books'), ('Middle Grade', 'Middle Grade'), ('Textbooks', 'Textbooks'), ('Research Papers', 'Research Papers'), ('Journals', 'Journals'), ('Academic Monographs', 'Academic Monographs'), ('Reference Books', 'Reference Books'), ('Contemporary Poetry', 'Contemporary Poetry'), ('Classic Poetry', 'Classic Poetry'), ('Epic Poetry', 'Epic Poetry'), ('Sonnets', 'Sonnets'), ('Personal Development', 'Personal Development'), ('Relationships', 'Relationships'), ('Motivation', 'Motivation'), ('Mindfulness', 'Mindfulness'), ('Travel Guides', 'Travel Guides'), ('Adventure Travel', 'Adventure Travel'), ('Travel Memoirs', 'Travel Memoirs'), ('Travel Essays', 'Travel Essays'), ('Entrepreneurship', 'Entrepreneurship'), ('Management', 'Management'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Leadership', 'Leadership'), ('else', 'Else')], max_length=50)),
                ('category', models.CharField(choices=[('Fiction', 'Fiction'), ('Non fiction', 'Non Fiction'), ('Childrens Books', 'Childrens Books'), ('Academic Books', 'Academic Books'), ('Poetry', 'Poetry'), ('Self-help', 'Self Help'), ('Travel', 'Travel'), ('Business', 'Business'), ('else', 'Else')], max_length=50)),
                ('publication_date', models.DateField()),
                ('rating', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookstoreWeb.author')),
            ],
        ),
    ]
